seed: 42

data:
  base_dir: /Users/yuzi/Desktop/physionet.org/files/ptb-xl/1.0.3
  fs: 500
  leads: 12
  normalize: per_lead
  min_occ: 50
  labels: ["MI", "STTC", "HYP", "CD", "NORM"] # 建议直接用5大类
  split: "strat_fold_9"

train:
  batch_size: 64
  epochs: 30
  optimizer: "adamw"
  lr: 1.5e-3
  weight_decay: 1e-4
  amp: true
  early_stop_patience: 8

metrics:
  main: "auprc_macro"
  thresholds: "search_per_class"

model:
  ecg:
    in_leads: 12
    feat_dim: 256

log:
  out_dir: "outputs"
  tb: true
